CREATE TABLE [dbo].[Cart] (
    [CartID] INT IDENTITY (1, 1) NOT NULL,
    [UserID] INT NOT NULL,
    CONSTRAINT [PK__Cart__51BCD797ADEEB004] PRIMARY KEY CLUSTERED ([CartID] ASC),
    CONSTRAINT [FK__Cart__UserID__3A81B327] FOREIGN KEY ([UserID]) REFERENCES [dbo].[Users] ([UserID]),
    CONSTRAINT [UQ__Cart__1788CCAD45D8D13B] UNIQUE NONCLUSTERED ([UserID] ASC)
);

